### PR TITLE
this was just a simple file.

### PR DESCRIPTION
**Pull request by jmaih**

### CODE REVIEW

**Comment by spinwido** [comment]
Hi Junior! It's Nicole (from the FRB ATL - but now in Mannheim) :grinning:

**Comment by jmaih** [comment]
Hi Nicole,

so good to hear from you. How did you land in Mannheim?

**Comment by spinwido** [comment]
@jmaih , I got an Assistant Prof job in Political Science.

**Comment by jmaih** [comment]
So good to hear that. Then you must have run into a good friend of mine
Johannes Pfeifer?

## 

"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)

**Comment by spinwido** [comment]
I know of him but not super well. I think we met once or twice!

**Comment by jmaih** [comment]
Since you are in Europe I guess we will meet at some conference or event
one of these days.

## 

"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)

**Pull request merged**
